blank_issues_enabled: false
contact_links:
  - name: "💡 QUESTIONS"
    url: https://github.community/
    about: Visit Stack Overflow to ask questions or request for any other support.
  - name: "💬 CHAT"
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
